import React from 'react';
import { PageLayout } from './PageLayout';
import { useDecision } from '../context/DecisionContext';

const TermsContent = () => {
  const { t } = useDecision();
  return (
    <div className="w-full max-w-3xl mx-auto py-xl px-lg">
      <div className="mb-xl">
        <h1 className="text-display-xl mb-md">{t('terms.title')}</h1>
        <p className="text-body-md text-mute mb-lg">
          Last updated: June 17, 2026
        </p>
      </div>

      <div className="flex flex-col gap-xl text-body-md text-body">
        <section className="flex flex-col gap-sm">
          <h2 className="text-heading-sm font-semibold text-ink">1. Agreement to Terms</h2>
          <p className="leading-relaxed">
            By accessing or using our website, you agree to be bound by these Terms and Conditions and our Privacy Policy. If you do not agree with any part of these terms, you must not use our services.
          </p>
        </section>

        <section className="flex flex-col gap-sm">
          <h2 className="text-heading-sm font-semibold text-ink">2. Use of Service</h2>
          <p className="leading-relaxed">
            Decision Maker provides tools for generating random choices. While we strive for fairness and randomness, the results are for entertainment and informational purposes only. We are not responsible for any decisions made based on the results generated by our tools.
          </p>
        </section>

        <section className="flex flex-col gap-sm">
          <h2 className="text-heading-sm font-semibold text-ink">3. Intellectual Property</h2>
          <p className="leading-relaxed">
            The content, features, and functionality of Decision Maker are and will remain the exclusive property of Decision Maker and its licensors. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of Decision Maker.
          </p>
        </section>

        <section className="flex flex-col gap-sm">
          <h2 className="text-heading-sm font-semibold text-ink">4. Limitation of Liability</h2>
          <p className="leading-relaxed">
            In no event shall Decision Maker, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses.
          </p>
        </section>

        <section className="flex flex-col gap-sm">
          <h2 className="text-heading-sm font-semibold text-ink">5. Governing Law</h2>
          <p className="leading-relaxed">
            These Terms shall be governed and construed in accordance with the laws of your jurisdiction, without regard to its conflict of law provisions.
          </p>
        </section>

        <section className="flex flex-col gap-sm">
          <h2 className="text-heading-sm font-semibold text-ink">6. Contact Us</h2>
          <p className="leading-relaxed">
            If you have any questions about these Terms, please contact us through our contact page.
          </p>
        </section>

        <div className="mt-xl pt-xl border-t border-hairline">
          <a href="/" className="text-link hover:text-link-deep font-medium flex items-center gap-xs">
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" /></svg>
            {t('nav.home')}
          </a>
        </div>
      </div>
    </div>
  );
};

export const TermsView = () => {
  return (
    <PageLayout>
      <TermsContent />
    </PageLayout>
  );
};
